#  _
# | |_ _ __ ___  _   ___  __
# | __| '_ ` _ \| | | \ \/ /
# | |_| | | | | | |_| |>  <
#  \__|_| |_| |_|\__,_/_/\_\


# General
set-option -g default-terminal "tmux-256color"
set-option -ag terminal-overrides ",*:RGB"
set-option -g history-limit 10000
set-option -s escape-time 0
set-option -g mouse on
set-option -g focus-events on
set-option -g set-clipboard on
set-option -g allow-passthrough on
set-option -g detach-on-destroy off
set-option -g renumber-windows on
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Status
set-option -g status-position top
set-option -g status-interval 5
set-option -g status 2
set-option -g status-format[1] ""
set-option -g status-style "bg=default,fg=default"
set-option -g status-left-length 30
set-option -g status-left "#[bg=blue,fg=black] #{session_name} #[bg=default] "
set-option -g status-right-length 50
set-option -g status-right "#[bg=default,fg=blue]#{?client_prefix,PREFIX,}#{?window_zoomed_flag, ZOOM,}"
set-option -g message-style "fill=terminal,bg=default,fg=blue"
set-option -g message-command-style "fill=terminal,bg=default,fg=blue"
set-window-option -g window-status-separator ""
set-window-option -g window-status-format "#[bg=default,fg=blue] #{window_index}:#{window_name} "
set-window-option -g window-status-current-format "#[bg=default,fg=yellow] #{window_index}:#{window_name} "
set-option -g pane-border-style "fg=brightblack"
set-option -g pane-active-border-style "fg=blue"
set-option -g mode-style "bg=blue,fg=black"

# Prefix
unbind-key C-b
set-option -g prefix C-Space
bind-key -N "Send prefix" C-Space send-prefix

# Reload Configuration
bind-key -N "Reload configuration" q source-file $XDG_CONFIG_HOME/tmux/tmux.conf

# Copy Mode
set-window-option -g mode-keys vi
bind-key -N "Begin selection" -T copy-mode-vi v send-key -X begin-selection
bind-key -N "Copy selection" -T copy-mode-vi y send-key -X copy-selection-and-cancel

# Session Keybindings
bind-key -N "Create session" C new-session
bind-key -N "Kill session" K kill-session
bind-key -N "Rename session" R command-prompt -I "#{session_name}" "rename-session -- '%%'"
bind-key -N "Open session picker" S run-shell "tmux neww tmux-sessionizer"
bind-key -N "Previous session" -n M-P switch-client -p
bind-key -N "Next session" -n M-N switch-client -n

# Window Keybindings
bind-key -N "Create window" c new-window -c "#{pane_current_path}"
bind-key -N "Kill window" k kill-window
bind-key -N "Rename window" r command-prompt -I "#{window_name}" "rename-window -- '%%'"
bind-key -N "Previous window" -n M-p select-window -t -1
bind-key -N "Next window" -n M-n select-window -t +1
bind-key -N "Switch to window 1" -n M-1 select-window -t 1
bind-key -N "Switch to window 2" -n M-2 select-window -t 2
bind-key -N "Switch to window 3" -n M-3 select-window -t 3
bind-key -N "Switch to window 4" -n M-4 select-window -t 4
bind-key -N "Switch to window 5" -n M-5 select-window -t 5
bind-key -N "Switch to window 6" -n M-6 select-window -t 6
bind-key -N "Switch to window 7" -n M-7 select-window -t 7
bind-key -N "Switch to window 8" -n M-8 select-window -t 8
bind-key -N "Switch to window 9" -n M-9 select-window -t 9

# Pane Keybindings
bind-key -N "Split pane vertically" h split-window -v -c "#{pane_current_path}"
bind-key -N "Split pane horizontally" v split-window -h -c "#{pane_current_path}"
bind-key -N "Kill pane" x kill-pane
bind-key -N "Focus pane above" -n M-Up select-pane -U
bind-key -N "Focus pane below" -n M-Down select-pane -D
bind-key -N "Focus pane left" -n M-Left select-pane -L
bind-key -N "Focus pane right" -n M-Right select-pane -R
bind-key -N "Resize pane up" -n M-S-Up resize-pane -U 5
bind-key -N "Resize pane down" -n M-S-Down resize-pane -D 5
bind-key -N "Resize pane left" -n M-S-Left resize-pane -L 5
bind-key -N "Resize pane right" -n M-S-Right resize-pane -R 5
