#  _   _                      _
# | | | | ___  _ __ ___   ___| |__  _ __ _____      __
# | |_| |/ _ \| '_ ` _ \ / _ \ '_ \| '__/ _ \ \ /\ / /
# |  _  | (_) | | | | | |  __/ |_) | | |  __/\ V  V /
# |_| |_|\___/|_| |_| |_|\___|_.__/|_|  \___| \_/\_/


brew "tmux"
brew "starship"
brew "neovim"
brew "git"
brew "coreutils"
brew "fzf"
brew "zoxide"
brew "eza"
brew "fd"
brew "ripgrep"
brew "bat"
brew "jq"
brew "unar"
brew "nmap"
brew "just"
brew "postgresql"
brew "php"
brew "composer"

cask "karabiner-elements"
cask "hammerspoon"
cask "mos"
cask "google-chrome"
cask "obsidian"
cask "ghostty"
cask "visual-studio-code"
cask "claude-code"
cask "tailscale-app"
cask "docker-desktop"
cask "affinity"
cask "bambu-studio"
cask "discord"
cask "spotify"
cask "iina"
cask "flutter"
cask "font-geist"
cask "font-monaspace"

vscode "enkia.tokyo-night"
vscode "pkief.material-icon-theme"
vscode "ms-azuretools.vscode-containers"
vscode "ms-vscode.cpptools"
vscode "platformio.platformio-ide"
vscode "rust-lang.rust-analyzer"
vscode "golang.go"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "bmewburn.vscode-intelephense-client"
vscode "astro-build.astro-vscode"
vscode "bradlc.vscode-tailwindcss"
vscode "editorconfig.editorconfig"
vscode "biomejs.biome"
vscode "stylelint.vscode-stylelint"
vscode "yoavbls.pretty-ts-errors"
vscode "jock.svg"
