---
#  __  __       _
# |  \/  | __ _(_)_ __
# | |\/| |/ _` | | '_ \
# | |  | | (_| | | | | |
# |_|  |_|\__,_|_|_| |_|


- hosts: localhost
  gather_facts: true
  vars_files:
    - 'vars/config.yaml'
  vars:
    user_id: "{{ ansible_facts['user_id'] }}"
    user_gid: "{{ ansible_facts['user_gid'] }}"
    user_home: "{{ ansible_facts['env']['HOME'] }}"
  tasks:
    - import_tasks: "./tasks/homebrew.yaml"
      tags: homebrew
    - import_tasks: "./tasks/dotfiles.yaml"
      tags: dotfiles
    - import_tasks: "./tasks/development.yaml"
      tags: development
    - import_tasks: "./tasks/macos.yaml"
      tags: macos
