---
#                        ___  ____
#  _ __ ___   __ _  ___ / _ \/ ___|
# | '_ ` _ \ / _` |/ __| | | \___ \
# | | | | | | (_| | (__| |_| |___) |
# |_| |_| |_|\__,_|\___|\___/|___/


- name: Ensure that the macOS script can be executed
  ansible.builtin.file:
    path: ./files/scripts/macos.sh
    state: touch
    mode: a+x

- name: Run macOS script
  ansible.builtin.script: scripts/macos.sh
