#  ____  _                 _     _
# / ___|| |_ __ _ _ __ ___| |__ (_)_ __
# \___ \| __/ _` | '__/ __| '_ \| | '_ \
#  ___) | || (_| | |  \__ \ | | | | |_) |
# |____/ \__\__,_|_|  |___/_| |_|_| .__/
#                                 |_|


command_timeout = 200
add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

[character]
format = '$symbol '
success_symbol = '[❯](cyan)'
error_symbol = '[✗](red)'

[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
style = 'blue'
truncation_length = 0
read_only = '🔒'

[git_branch]
format = '[$branch]($style) '
style = 'purple'

[git_state]
format = '[\[$state( $progress_current/$progress_total)\]]($style) '
style = 'purple'

[git_status]
format = '[(*$untracked$modified$staged$renamed$deleted$conflicted )($ahead_behind$stashed )]($style)'
style = 'purple'
untracked = '​'
modified = '​'
staged = '​'
renamed = '​'
deleted = '​'
conflicted = '​'
up_to_date = ''
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
stashed = '≡'
