#!/bin/zsh
#        _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# Common
alias \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  ls="eza --icons=always --group-directories-first --all" \
  ll="eza --icons=always --group-directories-first --all --long --header --group" \
  ff="fzf --style=full --color=16 --preview 'bat --theme=base16 --color=always {}'" \
  mkd="mkdir -vp" \
  cp="cp -vi" \
  mv="mv -vi" \
  rm="grm -vI" \
  cat="bat --theme=base16"
lt() {eza --icons=always --group-directories-first --all --tree --level=$1}

# Apps
alias \
  nv="nvim" \
  g="git" \
  k="kubectl" \
  d="docker" \
  pn="pnpm"

# Utilities
alias \
  update="brew update; brew upgrade; brew autoremove; brew cleanup; zinit update --all" \
  updatenode="curl -fsSL https://get.pnpm.io/install.sh | sh; sed -i '' '/# pnpm/,/# pnpm end/d' '$ZDOTDIR/.zshrc'; pnpm env use --global lts" \
  rmdsstore="find . -type f -name '*.DS_Store' -ls -delete"
sshkg() {ssh-keygen -t ed25519 -C $1 -f ~/.ssh/$2}
