#!/bin/zsh
#        _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# Navigation
alias \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  p="cd ~/Projects" \
  fd='find . -type d -name' \
  ff='find . -type f -name' \
  ls="exa --group-directories-first -a" \
  ll="exa --group-directories-first -algh"
lt() {exa --group-directories-first -a --tree --level=$1}

# Common
alias \
  mkd="mkdir -vp" \
  cp="cp -vi" \
  mv="mv -vi" \
  rm="grm -vI" \
  grep="grep --color=auto"

# Apps
alias \
  c="code" \
  nv="nvim" \
  g="git" \
  m="make" \
  pn="pnpm"

# Miscellaneous
alias \
  update="brew update; brew upgrade; brew autoremove; brew cleanup" \
  updatenode="curl -fsSL https://get.pnpm.io/install.sh | sh; sed -i '' '/# pnpm/,/# pnpm end/d' '$ZDOTDIR/.zshrc'; pnpm env use --global lts" \
  rmdsstore="find . -type f -name '*.DS_Store' -ls -delete"
sshkg() {ssh-keygen -t ed25519 -C $1 -f ~/.ssh/$2}
tunnel() {cloudflared tunnel --protocol http2 --url localhost:$1}
