#!/bin/zsh
#        _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# Common
alias \
  update="sudo softwareupdate -i -a" \
  c="code" \
  g="git" \
  pn="pnpm"
sshkg() {ssh-keygen -t ed25519 -C $1 -f ~/.ssh/$2}

# Navigation
alias \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  p="cd ~/Projects"

# Directories & Files
alias \
  fd='find . -type d -name' \
  ff='find . -type f -name' \
  ls="gls -hN --color=auto --group-directories-first" \
  ll="ls -al" \
  mkd="mkdir -vp" \
  cp="cp -vi" \
  mv="mv -vi" \
  rm="grm -vI" \
  grep="grep --color=auto"

# Miscellaneous
alias \
  rmdsstore="find . -type f -name '*.DS_Store' -ls -delete" \
  fuckphp="rm -rf composer.lock vendor && composer clear-cache && composer update" \
  fuckjs="rm -rf pnpm-lock.yaml node_modules && pnpm install"
