#!/bin/sh
#        _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# System
alias update="sudo -- sh -c 'apt update && apt upgrade -y && apt autoremove -y && apt autoclean -y'"

# General
alias \
  mv="mv -vi" \
  cp="cp -vi" \
  rm="rm -vI" \
  mkd="mkdir -vp" \
  ls="ls -hN --color=auto --group-directories-first" \
  ll="ls -al" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Navigation
alias \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  .....="cd ../../../.." \
  ......="cd ../../../../.." \
  dl="cd /mnt/c/Users/Tim/Downloads" \
  box="cd /mnt/c/Users/Tim/Dropbox"

# Visual Studio Code
alias \
  coden="code -n ." \
  coder="code -r ."

# Git
alias \
  gac="git add . && git commit -m" \
  gaca="git add . && git commit --amend --no-edit" \
  gsh="git push origin" \
  gll="git pull --rebase origin" \
  gcl="git clone" \
  glog="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# Composer
alias \
  fuckphp="rm -rf vendor composer.lock && composer clear-cache && composer update"

# Node Package Manager
alias \
  fuckjs="rm -rf node_modules package-lock.json && npm install" \
  nid="npm install --save-prod" \
  nidd="npm install --save-dev" \
  no="npm outdated" \
  nu="npm update" \
  na="npm audit fix" \
  nd="npm run dev" \
  np="npm run prod"
