#!/bin/sh
#        _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# System & Programs
alias \
  update="sudo -- sh -c 'apt update && apt upgrade -y && apt autoremove -y && apt autoclean -y'" \
  e="$EDITOR" \
  g="git"

# Common
alias \
  mv="mv -vi" \
  cp="cp -vi" \
  rm="rm -vI" \
  mkd="mkdir -vp" \
  ls="ls -hN --color=auto --group-directories-first" \
  ll="ls -al" \
  grep="grep --color=auto" \
  diff="diff --color=auto"

# Navigation
alias \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  .....="cd ../../../.." \
  ......="cd ../../../../.." \
  dl="cd /mnt/c/Users/Tim/Downloads" \
  db="cd /mnt/c/Users/Tim/Dropbox" \
  p="cd /mnt/c/Users/Tim/Projects"

# SSH
sshn() {ssh-keygen -t rsa -b 4096 -C $1 -f ~/.ssh/$2}
ssha() {ssh-add ~/.ssh/$1}

# Composer
alias \
  fuckphp="rm -rf vendor composer.lock && composer clear-cache && composer update"

# npm
alias \
  fuckjs="rm -rf node_modules package-lock.json && npm install" \
  nid="npm install --save-prod" \
  nidd="npm install --save-dev" \
  no="npm outdated" \
  nu="npm update" \
  nd="npm run dev" \
  np="npm run prod"
